### PR TITLE
Fix build errors

### PR DESCRIPTION
**Pull request by andrewgdotcom**
A few small changes to improve the buildability:

* change moovweb/gokogiri to sergioangulo/gokogiri
* remove spodhuis references, replace with pgpkeys.eu or generic terms as appropriate
* add GO111MODULE:=off to Makefile
* update README to remove references to now-fixed brokenness

### CODE REVIEW

**Comment by andrewgdotcom** [comment]
Now tested on both golang-1.11 and golang-1.15

**Comment by andrewgdotcom** [comment]
Now supports JSON stats page parsing, so it should reliably spider Hockeypuck.

**Comment by philpennock** [comment]
IOU one review: not forgotten, just been too tired when done with work.  Sorry, will get to this "soon".

**Comment by andrewgdotcom** [comment]
BTW it's running now at https://spider.pgpkeys.eu

**Comment by philpennock** [comment]
Cool; rev=made webmaster probably needs to update, and I need to dig through the site CSS to figure out which bits were for the sks-peers page and which for my own query web UI; https://gist.github.com/philpennock/de8c51968a3fdba67952ef2af1fd4716 is the complete CSS I used, complete with stupid font loading.  https://web.archive.org/web/20170422031721/sks.spodhuis.org/sks-peers shows what it used to look like.

**Comment by andrewgdotcom** [comment]
One thing I haven't yet worked out how to do reliably is get the links in the HTML to go to the human-readable stats page instead of the machine-readable page. May have to create a separate function HumanUrl() in server_info.go to be sure...

**Review by philpennock — APPROVED** [review]

**Comment by philpennock** [comment]
Sorry for the delay in reviewing.  All looks good, merged.

Would you like to be made a maintainer?  And would you like to fork/promote or leave it where it is, or something else?

**Comment by andrewgdotcom** [comment]
Thanks!

I'm not a Go programmer - I read a book on it a few months ago, and hacked around with this and hockeypuck, but that's about as far as it goes. If you would like to make me a maintainer, thank you. I'll try my best not to break anything :-) I'm happy to leave it where it is unless you particularly want rid of it...?

**Comment by philpennock** [comment]
Invite sent; security knowledge and community engagement are more important than Go knowledge, and my Go was much worse when I wrote this code back in the Go 1.0 days, as a weekend hack-port from Python.  I've seen you on relevant mailing-lists and am happy to share admin.

I don't particularly want rid of it, but if there's a new community actively using it then I'm not going to stand in anyone's way as they manage it.  So the offer to let it amicably move is there, for the future, should it ever be needed.

Collab invite sent.

**Pull request merged**
